# Generated by Django 5.1.1 on 2024-09-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeform',
            name='Recipe_Image',
            field=models.ImageField(upload_to='cookingpage'),
        ),
    ]
