# Generated by Django 5.1.1 on 2024-09-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooking', '0003_recipeform_user_alter_recipeform_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeform',
            name='Recipe_counter',
            field=models.IntegerField(default=1),
        ),
    ]
