# Generated by Django 5.1.1 on 2024-10-03 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cooking', '0005_department_studentid_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['department']},
        ),
    ]
