# Generated by Django 5.1.1 on 2024-10-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cooking', '0008_reportcard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectmarks',
            unique_together={('student', 'subject')},
        ),
    ]
