# Generated by Django 5.1.1 on 2024-10-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooking', '0009_alter_subjectmarks_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
