# Generated by Django 5.1.1 on 2024-10-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooking', '0010_student_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('Phone_number', models.IntegerField()),
            ],
        ),
    ]
