# Generated by Django 5.1.1 on 2024-09-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
